### ISSUE TITLE
[Feature Request] Add Webui

### ISSUE THREAD

**Issue by Keeperorowner** [JingMatrix/NeoZygisk#1]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

about webui

### Describe the solution you'd like/描述你想要的解决方案

Added web_ui, currently zygisk_mod and rezygisk have open source WeBuIs for reference

**Comment by JingMatrix** [comment]
Why do you need a WebUI? I think currently the Action button gives a fairly clean view.
