### ISSUE TITLE
[Bug] Apatch install fail

### ISSUE THREAD

**Issue by Keeperorowner** [JingMatrix/NeoZygisk#2]
### Steps to reproduce/复现步骤

install Neozygisk

### Expected behaviour/预期行为

install sucess

### Actual behaviour/实际行为

install fail

### KernelSU Module List/KernelSU 模块列表

```Shell
Lsposed
```

### Zygisk Next version/Zygisk Next 版本

211

### Android version/Android 版本

15

### KernelSU version/KernelSU 版本

Apatch 11017

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[APatch_install_APM_log_2024-12-26-13-34-23.log](https://github.com/user-attachments/files/18249927/APatch_install_APM_log_2024-12-26-13-34-23.log)

**Comment by Chen-hai-0721** [comment]
@JingMatrix Is it not adapted to Apatch

**Comment by JingMatrix** [comment]
Not yet adapted to APatch, I will do that when APatch works with Android 16

**Comment by JingMatrix** [comment]
Just find out the APatch supports my device now, and it removed a detection point I was worried about.
But why NativeTest v30 cannot be opened with APatch? @Keeperorowner

**Comment by JingMatrix** [comment]
Support for APatch is done now.

**Comment by JingMatrix** [comment]
A strang Rust bug is fixed, please update to the latest CI

**Comment by JingMatrix** [comment]
I didn't understand what you described. The card?

**Comment by JingMatrix** [comment]
Could you please flash the debug version and upload the logs when you are stuck?
Use `adb` to save logs:
```
adb logcat > full.logs
```
