### ISSUE TITLE
[FALSE] Modules Gone?

### ISSUE THREAD

**Issue by Stillhard** [JingMatrix/NeoZygisk#3]
### Steps to reproduce/复现步骤

Modules like TS and PIF failed to run normally in latest action

### Expected behaviour/预期行为

Should run normally

### Actual behaviour/实际行为

Not running normally

### KernelSU Module List/KernelSU 模块列表

```Shell
Magisk
```

### Zygisk Next version/Zygisk Next 版本

fb3ac72

### Android version/Android 版本

11

### KernelSU version/KernelSU 版本

Alpha/Canary/Kitsune

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

Maybe

**Comment by JingMatrix** [comment]
Cannot reproduce, please fill in the details of your environment.
