### ISSUE TITLE
[Bug] daemon crashes after detecting multiple instances of root

### ISSUE THREAD

**Issue by aqtoo** [JingMatrix/NeoZygisk#5]
### Steps to reproduce/复现步骤

1. Have Magisk as your root
2. Install a custom kernel (Like N0Kernel which has KSU built in that I don't use)
3. Flash module and reboot

### Expected behaviour/预期行为

ReZygisk, Zygisk Next and regular Zygisk all detect just Magisk and work as expected

### Actual behaviour/实际行为

[NeoZygisk_action_log_2024-12-31T15.42.47.log](https://github.com/user-attachments/files/18282471/NeoZygisk_action_log_2024-12-31T15.42.47.log)

### KernelSU Module List/KernelSU 模块列表

```Shell
Magisk List:
NeoZygisk (by you!)
Play Integrity Fork (by osm0sis)
Twemoji (by crystal)
Zygisk LSPosed Fork (by you!)
Zygisk Assistant (by snake-4)
```

### Zygisk Next version/Zygisk Next 版本

NeoZygisk-v1-0.0.0.0-219-3496703-release

### Android version/Android 版本

14

### KernelSU version/KernelSU 版本

Magisk 28.1

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[NeoZygisk_action_log_2024-12-31T15.42.47.log](https://github.com/user-attachments/files/18282505/NeoZygisk_action_log_2024-12-31T15.42.47.log)

**Comment by aqtoo** [comment]
For the exact version, I got it from [here](https://github.com/JingMatrix/NeoZygisk/actions/runs/12548926425)

**Comment by JingMatrix** [comment]
Yeah, you shouldn't have multiple root implementations.
Zygisk will get confused, and it is less secure.

**Comment by aqtoo** [comment]
I'll try my best to resolve this, thanks!

**Comment by aqtoo** [comment]
I'll try my best to resolve this, thanks!
